services:
  postgres:
    image: postgres:10.6-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - ./docker/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  cache:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - 6379:6379
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@email.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
      