GET http://localhost:8089/Agreements/1
accept: */*

###
GET http://localhost:8089/Agreements/2
accept: */*

###
GET http://localhost:8089/Agreements/3
accept: */*

###
GET https://localhost:7200/state
accept: */*