GET https://localhost:7200/Agreements/id?id=1
accept: */*

###
GET https://localhost:7200/Agreements/id?id=2
accept: */*

###
GET https://localhost:7200/Agreements/id?id=3
accept: */*

###
GET https://localhost:7200/state
accept: */*